name: undefinable
description: Distinguish between defined and undefined values in Dart.
repository: https://github.com/java-james/undefinable

platforms:
  android:
  ios:
  linux:
  macos:
  web:
  windows:

issue_tracker: https://github.com/java-james/undefinable/issues

environment:
  sdk: ^3.3.0

dependencies:

dev_dependencies:
  lints: ^6.0.0
  test: ^1.24.0
